FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["f:\\GitRepos\\tinyAlgebra\\src\\tA.bf", "f:\\GitRepos\\tinyAlgebra\\src\\Vector3.bf", "f:\\GitRepos\\tinyAlgebra\\src\\Vector2.bf", "f:\\GitRepos\\tinyAlgebra\\src\\Vector4.bf", "f:\\GitRepos\\tinyAlgebra\\src\\Mat4.bf", "f:\\GitRepos\\tinyAlgebra\\src\\Quaternion.bf"]

[MainWindow]
X = -2439
Y = 134
Width = 1200
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 248.0
SizePriority = 0.5007818
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 1077.0
SizePriority = 1077.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 278.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 112.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 2277.0
RequestedHeight = 150.0
SizePriority = 0.5280702
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Quaternion.bf"
TabWidth = 108.0
Type = "SourceViewPanel"
FilePath = "f:\\GitRepos\\tinyAlgebra\\src\\Quaternion.bf"
CursorPos = 387
ProjectName = "tinyAlgebra"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Mat4.bf"
TabWidth = 72.66666
Type = "SourceViewPanel"
FilePath = "f:\\GitRepos\\tinyAlgebra\\src\\Mat4.bf"
CursorPos = 994
ProjectName = "tinyAlgebra"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Vector4.bf"
TabWidth = 86.66666
Type = "SourceViewPanel"
FilePath = "f:\\GitRepos\\tinyAlgebra\\src\\Vector4.bf"
CursorPos = 1457
ProjectName = "tinyAlgebra"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Vector2.bf"
TabWidth = 86.66666
Type = "SourceViewPanel"
FilePath = "f:\\GitRepos\\tinyAlgebra\\src\\Vector2.bf"
ProjectName = "tinyAlgebra"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Vector3.bf"
TabWidth = 86.66666
Type = "SourceViewPanel"
FilePath = "f:\\GitRepos\\tinyAlgebra\\src\\Vector3.bf"
CursorPos = 2737
VertPos = 3700.586
ProjectName = "tinyAlgebra"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "tA.bf"
TabWidth = 56.0
Type = "SourceViewPanel"
FilePath = "f:\\GitRepos\\tinyAlgebra\\src\\tA.bf"
CursorPos = 11375
VertPos = 10843.0
ProjectName = "tinyAlgebra"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 221.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.4700162
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 97.33334
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.33334
Type = "WatchPanel"
Columns = [{Width = 240.0}, {Width = 240.0}, {Width = 240.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 76.66666
Type = "AutoWatchPanel"
Columns = [{Width = 240.0}, {Width = 240.0}, {Width = 240.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5299838
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 94.66666
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 109.3333
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 89.33334
Type = "OutputPanel"

[DebuggerDisplayTypes.""]
IntDisplayType = "Default"
MmDisplayType = "Default"
